### ISSUE TITLE
規劃大地遊戲底層架構

### ISSUE THREAD

**Issue by hashman** [MOPCON/Game-Server#2]

**Comment by xwang0929** [comment]
先用[這個](https://app.swaggerhub.com/apis/xwang0929/game-server/0.1.0)來討論。

幾個問題：
- 關卡跟任務需要配合或綁死嗎？從文件上看來兩個沒有直接的關係
- /verify/{vType} 拿來處理過關和核銷獎勵，帶任務或獎歷的 uuid 加上密碼就可以改寫
- 關卡、任務、獎勵的欄位需要跟 app team 討論嗎？

**Comment by hashman** [comment]
> 先用[這個](https://app.swaggerhub.com/apis/xwang0929/game-server/0.1.0)來討論。
> 
> 幾個問題：
> 
> * 關卡跟任務需要配合或綁死嗎？從文件上看來兩個沒有直接的關係

沒有關係，任務都是隨機配送的

> * /verify/{vType} 拿來處理過關和核銷獎勵，帶任務或獎勵的 uuid 加上密碼就可以改寫

ok 這個設計目前看起來沒問題

> * 關卡、任務、獎勵的欄位需要跟 app team 討論嗎？

我們這邊可以先開出來然後將 API 給他們看看

**Comment by hashman** [comment]
這個已經完成了
