### ISSUE TITLE
大地遊戲 Stage 1 API 完成

### ISSUE THREAD

**Issue by hashman** [MOPCON/Game-Server#3]
針對已經討論完的 [API Document](https://app.swaggerhub.com/apis/xwang0929/game-server/0.1.0) 進行製作，這邊麻煩中哥幫忙，謝謝

**Comment by xwang0929** [comment]
@hashman 

這是從 postman 匯出的檔案， paw 應該可以直接匯入後使用。可以拿這個來試試 api。

https://drive.google.com/open?id=1fKkSuXpmfB7QFrMZZVRUs_7ropKZUZG5

**Comment by xwang0929** [comment]
@hashman 

這是從 postman 匯出的檔案， paw 應該可以直接匯入後使用。可以拿這個來試試 api。

(兩個是同一個檔案)
https://drive.google.com/open?id=1fKkSuXpmfB7QFrMZZVRUs_7ropKZUZG5

[game server.postman_collection.json.zip](https://github.com/MOPCON/Game-Server/files/3532341/game.server.postman_collection.json.zip)

**Comment by hashman** [comment]
目前還有幾個 API 需要調整，這個 issue 我就暫時先不要關掉了
